[package]
name = "chrono_rabbit"
version = "0.1.0"
authors = ["asheraryam <asheraryam@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.11"
serenity = "0.8.6"
task_scheduler = "0.2.0"
parking_lot = "0.10.2"